version: '3.8'

services:
  # MongoDB Database
  mongodb:
    container_name: librechat-mongodb
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-LibreChat}
    networks:
      - librechat-network
    ports:
      - "27017:27017"

  # Redis Cache
  redis:
    container_name: librechat-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - librechat-network
    command: redis-server --appendonly yes

  # LibreChat Application
  librechat:
    container_name: librechat-app
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    ports:
      - "${LIBRECHAT_PORT:-3080}:3080"
    environment:
      # Database Configuration
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DB_NAME:-LibreChat}?authSource=admin
      
      # Redis Configuration
      REDIS_URI: redis://redis:6379
      
      # Application Configuration
      HOST: localhost
      PORT: 3080
      NODE_ENV: production
      
      # Security
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      CREDS_KEY: ${CREDS_KEY}
      CREDS_IV: ${CREDS_IV}
      
      # OpenAI API Key
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
      # Session Configuration
      SESSION_EXPIRY: ${SESSION_EXPIRY:-900000}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY:-604800000}
      
      # Registration
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION:-true}
      
      # Logging
      DEBUG_LOGGING: ${DEBUG_LOGGING:-true}
      
      # File uploads
      CDN_PROVIDER: ${CDN_PROVIDER:-}
      
      # MCP Configuration
      MCP_ENABLED: "true"
      
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
      - librechat_uploads:/app/client/public/images
      - librechat_logs:/app/api/logs
    networks:
      - librechat-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  librechat_uploads:
    driver: local
  librechat_logs:
    driver: local

networks:
  librechat-network:
    driver: bridge
