# =============================================================================
# LibreChat Configuration for v1.2.8
# =============================================================================

version: 1.2.8
cache: true

# MCP Servers Configuration
mcpServers:
  the_megaphone:
    type: streamable-http
    url: "https://7bec216a-1f3e-49b7-af7b-a730d84de27f-00-1b28s6q3zwadm.janeway.replit.dev"
    timeout: 30000
    headers:
      Authorization: "Token dev-api-key-12345; userId={{LIBRECHAT_USER_ID}}"
      X-User-Name: "{{LIBRECHAT_USER_USERNAME}}"
      X-User-Email: "{{LIBRECHAT_USER_EMAIL}}"
    serverInstructions: |
      AVAILABLE TOOLS & USAGE:
                  
                  ### megaphone_shortcuts Tool
                  **MANDATORY ROUTING**: If user message matches pattern ^[a-z]$ (single letter only), you MUST call megaphone_shortcuts with the exact text. Never decide availability yourself; let the tool validate.
                  **Recognition**: When user message contains ONLY a single letter (e.g., "m", "n", "y")
                  **Purpose**: Process quick shortcut commands for instant access to common Megaphone features
                  **How to use**: Call megaphone_shortcuts with the exact single letter as the parameter
                  
                  **Available Shortcuts**:
                  - **"a"**: Shows autopost guide (encourages posting)
                    - Provides encouraging guidance for sharing content
                    - Includes examples and step-by-step flow
                    - Reduces posting hesitation with friendly prompts
                    - Example: "🚀 Ready to Autopost! Just type your topic..."
                  
                  - **"h"**: Shows help with all available shortcuts
                    - Returns complete list of shortcuts with descriptions
                    - Single point of truth for all shortcuts
                    - Example: "🔥 Megaphone Shortcuts Help..."
                  
                  - **"m"**: Shows the user's display name in The Megaphone system
                    - Returns user's registered name or setup guidance if not found
                    - Example: "Your name in The Megaphone: John Smith"
                  
                  - **"n"**: Shows recent topics from the last 7 days  
                    - Returns list of recent discussions and activity
                    - Equivalent to searching for "recent topics" but faster
                    - Shows titles, authors, and timestamps
                  
                  - **"y"**: Shows your personal stats and engagement metrics
                    - Returns topics created, posts written, likes received
                    - Shows total engagement and most popular content
                    - Motivational feedback to encourage participation
                    - Example: "📊 Your Megaphone Stats - Topics: 3, Posts: 12, Likes: 8"
                  
                  - **"q"**: Shows unanswered questions where you can help
                    - Returns topics with few or no replies from last 2 weeks
                    - Excludes your own topics to show where you can contribute
                    - Encourages community participation and knowledge sharing
                    - Example: "❓ Unanswered Questions - 5 topics that could use your input"
                  
                  - **"s"**: Shows sharing ideas and contribution suggestions
                    - Returns personalized suggestions for what to share or contribute
                    - Adapts to current community activity levels and popular topics
                    - Provides specific topic templates and sharing prompts
                    - Example: "💡 Quick Share Ideas - Here are ways you could contribute..."
                  
                  - **"t"**: Shows topics you created (your own discussions)
                    - Lists your own discussions from The Megaphone
                    - Shows creation dates, reply counts, and tags
                    - Includes personalized message with your name
                    - Example: "📝 Your Topics - Shows your 5 discussions with reply counts"
                  
                  - **"u"**: Shows your unanswered questions (topics needing follow-up)
                    - Lists your own topics that haven't received many replies
                    - Focuses on topics you created that could use more discussion
                    - Includes motivational suggestions for follow-up actions
                    - Example: "❓ Your Topics Needing Follow-Up - 3 discussions that could use more input"
                  
                  - **"r"**: Shows recent replies to your content (who's responding)
                    - Lists recent replies to topics you created and posts you made
                    - Shows who replied, when, and preview of their response
                    - Focuses on last 7 days of activity to your content
                    - Example: "💬 Recent Replies to Your Content - 5 people responded to your content"
                  
                  **Usage Pattern**:
                  ```
                  User types: m
                  You call: megaphone_shortcuts with shortcut: "m"
                  You respond: [Clean response from the tool]
                  ```
                  
                  **Important**: 
                  - Only use this tool for exact shortcut patterns (single letter only)
                  - Don't explain what the shortcut does, just process it naturally
                  - Present the returned information directly to the user
                  - If shortcut is unknown, the tool will provide available options
                  
                  ### 1. ensure_identity
                  **Purpose**: Authenticate and verify user identity in the system
                  **When to use**: ALWAYS call this FIRST in every conversation - it's required for all other operations
                  **Never mention**: Don't tell users about this step - it's a technical requirement
                  **What it returns**: User confirmation and system readiness
                  
                  ### 2. search_megaphone
                  **Purpose**: Find existing knowledge, discussions, and information
                  **When to use**: 
                    - User asks about any topic, policy, project, or information
                    - Before creating new content (check if similar exists)
                    - When connecting related conversations
                    - To discover context about ongoing projects or decisions
                  **What it searches**: Full content across all topics, posts, and discussions
                  **How to use**: Use natural language queries, specific keywords, or topic areas
                  **Returns**: Relevant discussions with context, authors, and timestamps
                  
                  ### 3. create_topic
                  **Purpose**: Start new discussions or share information with the team
                  **When to use**:
                    - User wants to make announcements
                    - Sharing new information, updates, or decisions
                    - Starting discussions about projects or policies
                    - Recording important information for future reference
                  **What it creates**: New discussion thread that others can find and reply to
                  **Auto-features**: Intelligent tagging, semantic indexing, language detection
                  
                  ### 4. reply_to_topic
                  **Purpose**: Add to existing conversations and discussions
                  **When to use**:
                    - Responding to ongoing discussions
                    - Adding updates to existing topics
                    - Providing additional context or information
                    - Continuing conversations started by others
                  **What it does**: Adds threaded responses that maintain conversation context
                  
                  ### 5. get_topic
                  **Purpose**: Retrieve full discussion threads with all replies
                  **When to use**:
                    - User wants to see complete conversation history
                    - Need to understand full context of a discussion
                    - Reviewing detailed information from previous conversations
                  **What it returns**: Complete topic with all replies, metadata, and engagement
                  
                  ### 6. like_post
                  **Purpose**: Show appreciation or agreement with content
                  **When to use**:
                    - Content is helpful, interesting, or valuable
                    - Showing team support or agreement
                    - Highlighting important information for others
                  **Natural expression**: Do this when you genuinely find content valuable
                  
                  ### 7. list_recent_topics
                  **Purpose**: Show latest team activity and discussions
                  **When to use**:
                    - User wants to catch up on recent activity
                    - Discovering what's currently being discussed
                    - Finding active conversations to join
                  **What it returns**: Recent topics with activity summaries and engagement metrics

# Endpoints Configuration
endpoints:
  agents:
    disableBuilder: false
    recursionLimit: 50
    maxRecursionLimit: 100
    capabilities:
      - execute_code
      - file_search
      - actions
      - tools
      - artifacts
      - web_search
    maxCitations: 30
    maxCitationsPerFile: 7
    minRelevanceScore: 0.45
  openAI:
    title: "OpenAI"
    apiKey: "${OPENAI_API_KEY}"
    models:
      fetch: true
    dropParams:
      - "frequency_penalty"
      - "presence_penalty"
      - "stop"
      - "user"
    titleConvo: true
    titleModel: "gpt-3.5-turbo"

# Interface Configuration
interface:
  agents: true
  temporaryChatRetention: 720

# File Configuration
fileConfig:
  endpoints:
    openAI:
      disabled: false
      fileLimit: 5
      fileSizeLimit: 10
      totalSizeLimit: 50
      supportedMimeTypes:
        - "text/plain"
        - "application/pdf"
        - "image/jpeg"
        - "image/png"
        - "image/webp"



# Rate Limits
rateLimits:
  fileUploads:
    ipMax: 500
    ipWindowInMinutes: 60
    userMax: 50
    userWindowInMinutes: 60
  conversationsImport:
    ipMax: 500
    ipWindowInMinutes: 60
    userMax: 10
    userWindowInMinutes: 60
  stt:
    ipMax: 500
    ipWindowInMinutes: 1
    userMax: 100
    userWindowInMinutes: 1
  tts:
    ipMax: 500
    ipWindowInMinutes: 1
    userMax: 100
    userWindowInMinutes: 1

# Memory Configuration
# Memory system is disabled

# Web Search Configuration
webSearch:
  searchProvider: "serper"
  scraperType: "serper"
  rerankerType: "jina"
  safeSearch: 1
  scraperTimeout: 10000
  serperApiKey: "${SERPER_API_KEY}"
  searxngApiKey: "${SEARXNG_API_KEY}"
  searxngInstanceUrl: "${SEARXNG_INSTANCE_URL}"
  firecrawlApiKey: "${FIRECRAWL_API_KEY}"
  jinaApiKey: "${JINA_API_KEY}"
  cohereApiKey: "${COHERE_API_KEY}"

# OCR Configuration
ocr:
  strategy: "mistral_ocr"
  mistralModel: "mistral-ocr-latest"
  apiKey: "${OCR_API_KEY}"
  baseURL: "${OCR_BASEURL}"

# Actions Configuration
# Actions are not configured

