# =============================================================================
# LibreChat Configuration for v0.8.0-RC4
# =============================================================================

version: 1.2.8
cache: true

# MCP Servers Configuration
mcpServers:
  the_megaphone:
    type: streamable-http
    url: "https://7bec216a-1f3e-49b7-af7b-a730d84de27f-00-1b28s6q3zwadm.janeway.replit.dev"
    timeout: 30000
    headers:
      Authorization: "Token dev-api-key-12345; userId={{LIBRECHAT_USER_ID}}"
      X-User-Name: "{{LIBRECHAT_USER_USERNAME}}"
      X-User-Email: "{{LIBRECHAT_USER_EMAIL}}"
    

# Endpoints Configuration
endpoints:
  agents:
    disableBuilder: false
    recursionLimit: 50
    maxRecursionLimit: 100
    capabilities:
      - execute_code
      - file_search
      - actions
      - tools
      - artifacts
      - web_search
    maxCitations: 30
    maxCitationsPerFile: 7
    minRelevanceScore: 0.45
  openAI:
    title: "OpenAI"
    apiKey: "${OPENAI_API_KEY}"
    models:
      fetch: true
    dropParams:
      - "frequency_penalty"
      - "presence_penalty"
      - "stop"
      - "user"
    titleConvo: true
    titleModel: "gpt-3.5-turbo"

# Interface Configuration
interface:
  agents: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: false
  webSearch: true
  fileSearch: true
  fileCitations: true
  runCode: true
  temporaryChatRetention: 720

# File Configuration
fileConfig:
  endpoints:
    openAI:
      disabled: false
      fileLimit: 5
      fileSizeLimit: 10
      totalSizeLimit: 50
      supportedMimeTypes:
        - "text/plain"
        - "application/pdf"



# Rate Limits
rateLimits:
  fileUploads:
    ipMax: 100
    ipWindowInMinutes: 60
    userMax: 50
    userWindowInMinutes: 60
  conversationsImport:
    ipMax: 100
    ipWindowInMinutes: 60
    userMax: 50
    userWindowInMinutes: 60
  stt:
    ipMax: 100
    ipWindowInMinutes: 1
    userMax: 50
    userWindowInMinutes: 1
  tts:
    ipMax: 100
    ipWindowInMinutes: 1
    userMax: 50
    userWindowInMinutes: 1

# Memory Configuration
# Memory system is disabled

# Web Search Configuration
# Web search is not configured

# OCR Configuration
# OCR is not configured

# Actions Configuration
# Actions are not configured

